### ISSUE TITLE
the hyper-parameter

### ISSUE THREAD

**Issue by ghost** [tensorboy/PIDOptimizer#1]
你好，请问能详细解释一下参数的确定嘛

**Comment by tensorboy** [comment]
应该最主要的参数就是Ｋ_d了，论文里有个理论建议值，不过大多数时候还是要调一下。

**Comment by lshiwjx** [comment]
您好, 请问论文中cifar10数据上的K_d是多少

**Comment by tensorboy** [comment]
We didn't release the K_d on cifar yet. :-D
