### ISSUE TITLE
Why D is added rather than being subtracted in Eq.10

### ISSUE THREAD

**Issue by lshiwjx** [tensorboy/PIDOptimizer#3]
The sign of D in Eq.10 is +:
![image](https://user-images.githubusercontent.com/17141689/43750544-8874c0c4-9a2b-11e8-92ce-b768b247cf5f.png)
But it should be the same as I as shown in Eq.1:
![image](https://user-images.githubusercontent.com/17141689/43750626-e7d43bf8-9a2b-11e8-81ee-b8c267569b5b.png)

**Comment by tensorboy** [comment]
Hi, @lshiwjx 

The top equation is the moving average of D, and the bottom is the formula of PID.

**Comment by lshiwjx** [comment]
I am still confused.
Why the sign of D term is not the same as PI term in Eq.10.
